#!/usr/bin/env python3
import argparse
import os
import shutil
import re

# ------------------------------------------------------------
# Parse core ranges including stepped syntax
# e.g. 1-10,12-20%2,24-100%4
# ------------------------------------------------------------
def parse_core_ranges(ranges_str):
    cores = []
    for part in ranges_str.split(","):
        part = part.strip()
        if not part:
            continue

        if "%" in part:
            base, step = part.split("%")
            step = int(step)
        else:
            base, step = part, None

        if "-" in base:
            start, end = map(int, base.split("-"))
            if step:
                cores.extend(range(start, end + 1, step))
            else:
                cores.extend(range(start, end + 1))
        else:
            cores.append(int(base))

    return sorted(set(cores))


# ------------------------------------------------------------
# Convert memory-per-CPU into MB for ORCA %MAXCORE
# ------------------------------------------------------------
def convert_memory_to_mb(mem_str):
    mem_str = mem_str.upper().replace(" ", "")
    if mem_str.endswith(("GB", "G")):
        return int(float(mem_str.rstrip("GB").rstrip("G")) * 1024)
    if mem_str.endswith(("MB", "M")):
        return int(float(mem_str.rstrip("MB").rstrip("M")))
    raise ValueError(f"Unsupported memory format: {mem_str}")


# ------------------------------------------------------------
# Modify ORCA input safely (%PAL + %MAXCORE only)
# ------------------------------------------------------------
def modify_orca_input(src, dst, ncores, maxcore_mb):
    with open(src, "r") as f:
        text = f.read()

    pal_pattern = re.compile(r"(%PAL[\s\S]*?END)", flags=re.IGNORECASE)
    if pal_pattern.search(text):
        def repl(match):
            block = match.group(1)
            return re.sub(
                r"NPROCS\s+\d+",
                f"NPROCS {ncores}",
                block,
                flags=re.IGNORECASE,
            )
        text = pal_pattern.sub(repl, text)
    else:
        text = f"%PAL\n  NPROCS {ncores}\nEND\n" + text

    max_pattern = re.compile(r"%MAXCORE\s+\d+", flags=re.IGNORECASE)
    if max_pattern.search(text):
        text = max_pattern.sub(f"%MAXCORE {maxcore_mb}", text)
    else:
        text = f"%MAXCORE {maxcore_mb}\n" + text

    with open(dst, "w") as f:
        f.write(text)


# ------------------------------------------------------------
# Copy optional ORCA support data
# ------------------------------------------------------------
def copy_support_data(src_folder, dest_folder):
    if not os.path.isdir(src_folder):
        raise NotADirectoryError(f"Support data folder not found: {src_folder}")

    for item in os.listdir(src_folder):
        s = os.path.join(src_folder, item)
        d = os.path.join(dest_folder, item)
        if os.path.isdir(s):
            shutil.copytree(s, d, dirs_exist_ok=True)
        else:
            shutil.copy2(s, d)


# ------------------------------------------------------------
# Parse include file (SBATCH lines + ORCA version)
# ------------------------------------------------------------
def parse_include_file(path):
    sbatch_lines = []
    orca_version = None

    with open(path, "r") as f:
        for line in f:
            stripped = line.strip()
            if stripped.startswith("#SBATCH"):
                sbatch_lines.append(stripped)
            if stripped.lower().startswith("orca version:"):
                orca_version = stripped.split(":", 1)[1].strip()

    if not orca_version:
        raise ValueError("Include file MUST contain: ORCA version: ORCA/<version>")

    return sbatch_lines, orca_version


# ------------------------------------------------------------
# Create submit_array.sl (explicit array list)
# ------------------------------------------------------------
def create_array_submit_script(
    path,
    sbatch_lines,
    orca_version,
    array_string,
    max_cores,
    mem_per_cpu,
):
    header = [
        "#!/bin/bash -e",
        "",
        "# ============================================================",
        "# ORCA CPU Benchmarking Array Job",
        "#",
        "# This script was autogenerated by create_orca_benchmarking_v2.",
        "#",
        "# Each array index corresponds directly to the number of MPI cores.",
        "# ============================================================",
        "",
        f"#SBATCH --array={array_string}",
        f"#SBATCH --ntasks={max_cores}",
        f"#SBATCH --mem-per-cpu={mem_per_cpu}",
        "#SBATCH --gres=ssd:1",
    ]

    for line in sbatch_lines:
        if "--ntasks=" in line or "--mem-per-cpu=" in line:
            continue
        header.append(line)

    section1 = r"""
# ------------------------------------------------------------
# 1) SELECT PER-CORE WORKING DIRECTORY
# ------------------------------------------------------------
WORKDIR="${SLURM_ARRAY_TASK_ID}cores"
OUTPUTDIR=${PWD}/${WORKDIR}

echo "--------------------------------------------"
echo " SLURM_ARRAY_TASK_ID : $SLURM_ARRAY_TASK_ID"
echo " MPI cores           : $SLURM_ARRAY_TASK_ID"
echo " Working directory   : $WORKDIR"
echo "--------------------------------------------"

cd ${WORKDIR}
"""

    section2 = r"""
# ------------------------------------------------------------
# 2) STAGE JOB-SPECIFIC FILES INTO TMPDIR
# TMPDIR is node-local and very fast.
# ------------------------------------------------------------
export TMP_PATH=${TMPDIR}/${SLURM_ARRAY_JOB_ID}/${WORKDIR}

mkdir -p ${TMP_PATH}
cp -r orca.inp input.xyz ${TMP_PATH}
cd ${TMP_PATH}
"""

    section3 = f"""
# ------------------------------------------------------------
# 3) LOAD ORCA MODULE
# ------------------------------------------------------------
module load {orca_version}
"""

    section4 = r"""
# ------------------------------------------------------------
# 4) RUN ORCA
# ------------------------------------------------------------
orca_exe=$(which orca)
$orca_exe orca.inp > ${OUTPUTDIR}/orca.out
"""

    with open(path, "w") as f:
        f.write("\n".join(header) + "\n")
        f.write(section1)
        f.write(section2)
        f.write(section3)
        f.write(section4)


# ------------------------------------------------------------
# Main driver
# ------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Generate ORCA benchmarking folders + SLURM array job."
    )
    parser.add_argument("orca_input")
    parser.add_argument("include_file")
    parser.add_argument("--cores", required=True)
    parser.add_argument("--copy-data")
    parser.add_argument("--mem-per-cpu", required=True)

    args = parser.parse_args()

    core_list = parse_core_ranges(args.cores)
    array_string = ",".join(str(c) for c in core_list)  # ✅ EXPLICIT ARRAY LIST
    max_cores = max(core_list)
    maxcore_mb = convert_memory_to_mb(args.mem_per_cpu)

    sbatch_lines, orca_version = parse_include_file(args.include_file)

    bench_root = "orca_benchmarking"
    os.makedirs(bench_root, exist_ok=True)

    for n in core_list:
        folder = os.path.join(bench_root, f"{n}cores")
        os.makedirs(folder, exist_ok=True)

        modify_orca_input(
            args.orca_input,
            os.path.join(folder, "orca.inp"),
            n,
            maxcore_mb,
        )

        if args.copy_data:
            copy_support_data(args.copy_data, folder)

        print(f"✅ Created folder: {folder}")

    submit_path = os.path.join(bench_root, "submit_array.sl")
    create_array_submit_script(
        submit_path,
        sbatch_lines,
        orca_version,
        array_string,
        max_cores,
        args.mem_per_cpu,
    )

    print(f"\n✅ submit_array.sl written to: {submit_path}")
    print("✅ Done.")

def cli():
    main()
